# Generated by Django 5.1.3 on 2024-11-12 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_quiz_class_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongen',
            name='category',
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.DeleteModel(
            name='OptionGen',
        ),
        migrations.DeleteModel(
            name='QuestionGen',
        ),
    ]
